[package]
name = "debouncer"
version = "0.2.0"
edition = "2024"

[build-dependencies]
bindgen = "0.72.0"

[dependencies]
log = "0.4.27"
tokio = { version = "1.47.1", features = ["sync"] }
trpl = "0.2.0"
